import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class UserService {
  userData = [
    {
      name: 'Anshul Singh',
      email: 'anshulsinghchouhan4@gmail.com',
      phone: '9079410789',
      role: 'Admin',
      status: true,
      firstname: 'Anshul',
      lastname: 'Singh',
      dept: 'xyz',
      password: '12345678',
      confirmPassword: '12345678',
      address: 'Gurugram',
    },
    {
      name: 'Anshul Singh',
      email: 'anshulsinghchouhan4@gmail.com',
      phone: '9079410789',
      role: 'Admin',
      status: true,
      firstname: 'Anshul',
      lastname: 'Singh',
      dept: 'xyz',
      password: '12345678',
      confirmPassword: '12345678',
      address: 'Gurugram',
    },
    {
      firstname: 'kndks',
      lastname: 'knskdfn',
      role: 'Admin',
      dept: 'ksdnfk',
      email: 'ksdnfk@Knf.com',
      phone: '99999999999',
      password: 'ksdkfk',
      confirmPassword: 'nksdnfk',
      address: 'ksdnkf',
      status: false,
      name: 'kndks knskdfn',
    },
    {
      name: 'Anshul Singh',
      email: 'anshulsinghchouhan4@gmail.com',
      phone: '9079410789',
      role: 'Admin',
      status: true,
      firstname: 'Anshul',
      lastname: 'Singh',
      dept: 'xyz',
      password: '12345678',
      confirmPassword: '12345678',
      address: 'Gurugram',
    },
    {
      firstname: 'kndks',
      lastname: 'knskdfn',
      role: 'Admin',
      dept: 'ksdnfk',
      email: 'ksdnfk@Knf.com',
      phone: '99999999999',
      password: 'ksdkfk',
      confirmPassword: 'nksdnfk',
      address: 'ksdnkf',
      status: false,
      name: 'kndks knskdfn',
    },
    {
      firstname: 'kndks',
      lastname: 'knskdfn',
      role: 'Admin',
      dept: 'ksdnfk',
      email: 'ksdnfk@Knf.com',
      phone: '99999999999',
      password: 'ksdkfk',
      confirmPassword: 'nksdnfk',
      address: 'ksdnkf',
      status: false,
      name: 'kndks knskdfn',
    },
    {
      name: 'Anshul Singh',
      email: 'anshulsinghchouhan4@gmail.com',
      phone: '9079410789',
      role: 'Admin',
      status: true,
      firstname: 'Anshul',
      lastname: 'Singh',
      dept: 'xyz',
      password: '12345678',
      confirmPassword: '12345678',
      address: 'Gurugram',
    },
    {
      firstname: 'kndks',
      lastname: 'knskdfn',
      role: 'Admin',
      dept: 'ksdnfk',
      email: 'ksdnfk@Knf.com',
      phone: '99999999999',
      password: 'ksdkfk',
      confirmPassword: 'nksdnfk',
      address: 'ksdnkf',
      status: false,
      name: 'kndks knskdfn',
    },
    {
      firstname: 'kndks',
      lastname: 'knskdfn',
      role: 'Admin',
      dept: 'ksdnfk',
      email: 'ksdnfk@Knf.com',
      phone: '99999999999',
      password: 'ksdkfk',
      confirmPassword: 'nksdnfk',
      address: 'ksdnkf',
      status: false,
      name: 'kndks knskdfn',
    },
    {
      name: 'Anshul Singh',
      email: 'anshulsinghchouhan4@gmail.com',
      phone: '9079410789',
      role: 'Admin',
      status: true,
      firstname: 'Anshul',
      lastname: 'Singh',
      dept: 'xyz',
      password: '12345678',
      confirmPassword: '12345678',
      address: 'Gurugram',
    },
    {
      firstname: 'kndks',
      lastname: 'knskdfn',
      role: 'Admin',
      dept: 'ksdnfk',
      email: 'ksdnfk@Knf.com',
      phone: '99999999999',
      password: 'ksdkfk',
      confirmPassword: 'nksdnfk',
      address: 'ksdnkf',
      status: false,
      name: 'kndks knskdfn',
    },
  ];

  constructor() {}
}
